# Generated by Django 2.2.8 on 2020-08-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderconfirmation',
            name='cart_id',
        ),
    ]
