# Generated by Django 2.2.8 on 2020-09-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderconfirmation_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_on_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
