# Generated by Django 2.2.8 on 2020-10-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20200811_2352'),
        ('orders', '0005_auto_20201030_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='addresses.Address'),
        ),
    ]
