# Generated by Django 2.2.8 on 2020-10-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_shipping_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
