# Generated by Django 2.2.8 on 2020-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_refundgrandconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfirmation',
            name='cart_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
