# Generated by Django 2.2.8 on 2020-08-13 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderconfirmation_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfirmation',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
    ]
