# Generated by Django 2.2.8 on 2020-08-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200813_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfirmation',
            name='cart_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
