# Generated by Django 2.2.8 on 2020-08-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200813_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfirmation',
            name='cart_id',
            field=models.IntegerField(blank=True),
        ),
    ]
